spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/practice?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
  banner:
    location: classpath:/templates/banner.txt

#日志文件配置
logging:
  config: classpath:logback.xml
  level:
    com:
      dao: debug

mybatis:
  mapper-locations: classpath:/mybatis/*Mapper.xml
  type-aliases-package: com.hs.model
  config-location: classpath:mybatis-config.xml